baseurl = "/"
theme = "cocoa-eh-hugo-theme"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
#author = "Alexis Tacnet"
title = "Rene Welch"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Jan 2 2006"
description = "Example blog"
copyright = "Copyright © 2018 Rene Welch"
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = ""
faviconfile = ""
#logofile = "img/bike_snow_me.png"
#faviconfile = "img/logo.png"
highlightjs = true
progressively = true
share = true
latestpostcount = 5
github = "welch16"
email = "welch@stat.wisc.edu"
linkedin = "welch16"
twitter = "ReneWelch"
social_banner = "img/banner.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
#githubRepo = "githubUsername/repositoryName/tree/master"
small_banner_logo = false

[options]
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"

